name: ci
on:
  push:
    branches:
      - master
    pull_request:
jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
      - name: Gen test file
        run: make testfile
      - name: PR
        if: success()
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          base: master
          branch: testfile
          delete-branch: true
          commit-message: e2e test file is updated
          title: e2e changed
          body: |
            Auto pushed by bot
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
      - name: test
        run: make test
