name: ci
on:
  push:
    branches:
      - master
    pull_request:
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      code: ${{ steps.filter.outputs.code }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
  setup:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.code == 'true' }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: test
        run: make test
